### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by efecarranza** [Interque/interque#55]
hey, quick question.
so questions have tags, i see something called acts_as_taggable, but not sure how it works.
i cannot access Tags by themselves, how would i go about doing that?
because i want to get similar tags and stuff but not sure how to approach that

thanks

**Comment by toddmetheny** [comment]
this is cool. our first issue :) responded on Slack but acts_as_taggable_on is namespaced so to access the tags it's something like ActsAsTaggableOn::Tag.last to get the last tag.
