### ISSUE TITLE
Job board page scrolls to the side

### ISSUE THREAD

**Issue by albertog2man** [Interque/interque#57]
The job board page is weird and it scrolls to the side. It also asks me to either log in or signup even if I'm already signed in.

**Comment by toddmetheny** [comment]
Hey man. For the login thing...are you sure you have an account on jobs? It's a completely separate app with separate auth then interque. I know that's dumb and kind of sucks...but I don't think you have an account on the jobs site.

re: the viewport...thanks for pointing that out. Not sure why that's happening but was able to reproduce. Will try to take a look at and fix that over the holidays. Thanks for posting the issue!

**Comment by albertog2man** [comment]
Oh, no I don't have a job board login. But yea no problem.

**Comment by rbraaf** [comment]
@albertog2man Is this happening in any specific browsers or all of them?

**Comment by albertog2man** [comment]
Issue was found running chrome.

**Comment by toddmetheny** [comment]
Fixed by rbraaf. Thanks Alberto! Closing this issue.
